### ISSUE TITLE
ADR. Propuesta Integración de mapas en Front-End

### ISSUE THREAD

**Issue by franciscocoya** [Arquisoft/lomap_es5a#13]
## Integración de mapas en la aplicación

Completar la documentación relativa al ADR [https://github.com/Arquisoft/lomap_es5a/wiki/ADR.-Librer%C3%ADa-de-Mapas-%5BFront-End%5D](https://github.com/Arquisoft/lomap_es5a/wiki/ADR.-Librer%C3%ADa-de-Mapas-%5BFront-End%5D)

**Comment by UO282337** [comment]
Propuesta cerrada, elección confirmada
