### ISSUE TITLE
ADR. Propuesta y decisión en relación a la arquitectura a definir para el lado del cliente

### ISSUE THREAD

**Issue by franciscocoya** [Arquisoft/lomap_es5a#14]
## Arquitectura lado del cliente de la aplicación.

Tomar la decisión y completar la documentación relativa al ADR [https://github.com/Arquisoft/lomap_es5a/wiki/ADR.-Estructura-Cliente-%5BFront-End%5D](https://github.com/Arquisoft/lomap_es5a/wiki/ADR.-Estructura-Cliente-%5BFront-End%5D)

**Comment by RichardPix12** [comment]
Estructura de carpetas y proovedor SOLID definido.

**Comment by RichardPix12** [comment]
Estructura del cliente definida
