### ISSUE TITLE
ADR. Propuesta y decisión del despliegue de la aplicación.

### ISSUE THREAD

**Issue by franciscocoya** [Arquisoft/lomap_es5a#15]
## Despliegue de la aplicación

Decidir tecnologías a utilizar, infraestructura para ambos lados (Cliente y servidor) y servidor cloud. Documentar la decisión en el ADR [https://github.com/Arquisoft/lomap_es5a/wiki/ADR.-Despliegue-Aplicaci%C3%B3n-%5BCI-CD%5D](https://github.com/Arquisoft/lomap_es5a/wiki/ADR.-Despliegue-Aplicaci%C3%B3n-%5BCI-CD%5D)

**Comment by UO282337** [comment]
Decisión del despliegue aceptada.
