### ISSUE TITLE
API. Adaptación del ADD del punto con el uso del POD

### ISSUE THREAD

**Issue by miguelglez8** [Arquisoft/lomap_es5a#156]
Ahora se tendrán que guardar los puntos en el POD (de manera descentralizada)

**Comment by UO282337** [comment]
Estructura del JSON del punto:
"_id": "5a6c5b0b0f5a9c0014d1b1b1",
      "name": "Point 1",
      "description": "Point 1 description",
      "category": "",
      "isPublic": true,
      "location": {
        "address": "",
        "postalCode": 1111,
        "city": "City 1",
        "country": "Country 1",
        "coords": [0, 0]
      },
      "owner": {
        "webId": "https://localhost:8443/profile/card#me"
      },
      "reviews": [
        {
          "_id": "5a6c5b0b0f5a9c0014d1b1b2",
          "reviewer": {
            "webId": "https://localhost:8443/profile/card#me",
            "imageUrl": ""
          },
          "rating": 5,
          "comment": "This is a comment",
          "createdAt": "2018-01-24T15:00:00.000Z"
        }
      ],
      "createdAt": "2018-01-24T15:00:00.000Z",
      "updatedAt": "2018-01-24T15:00:00.000Z"
}

**Comment by UO282337** [comment]
Quedaría comprobar el tema de añadir (cuando no ha añadido todavia el usuario nada), y comprobar que la categoría se ha subido bien
