### ISSUE TITLE
Comenzar a investigar acerca de los test y el despliegue para la api

### ISSUE THREAD

**Issue by miguelglez8** [Arquisoft/lomap_es5a#157]
Investigación a fondo de las pruebas y el despliegue para la parte de la api

**Comment by UO282337** [comment]
Implementar pruebas

**Comment by UO271572** [comment]
Configuracion para realizar pruebas con jest realizado
- Pruebas en componentes para ver funcionamiento (Correcto)
Seguire actualizando en #182
