### ISSUE TITLE
ADR. Propuesta y decisión en relación a la arquitectura a definir para el lado del servidor

### ISSUE THREAD

**Issue by franciscocoya** [Arquisoft/lomap_es5a#16]
## Arquitectura lado del servidor

Decidir y documentar qué arquitectura va a tener el lado del servidor, comportamiento e integración de PODS de SOLID, así como la estructura de directorios. Enlace al ADR: [https://github.com/Arquisoft/lomap_es5a/wiki/ADR.-Estructura-Servidor-%5BBack-End%5D](https://github.com/Arquisoft/lomap_es5a/wiki/ADR.-Estructura-Servidor-%5BBack-End%5D)

**Comment by RichardPix12** [comment]
Decisiones tomadas y aceptadas por todos.
