### ISSUE TITLE
Decisión de la base de datos

### ISSUE THREAD

**Issue by UO282337** [Arquisoft/lomap_es5a#17]
Investigar acerca de qué base de datos elegir

**Comment by RichardPix12** [comment]
Decisiones tomadas : https://github.com/Arquisoft/lomap_es5a/wiki/ADR.--Base-de-datos

**Comment by UO282337** [comment]
Hemos tomado la decisión de cambiar la base de dato, debido a los siguientes [motivos](https://github.com/Arquisoft/lomap_es5a/wiki/ADR.-Cambio-a-base-de-datos-MongoDB)
