### ISSUE TITLE
Fix del login

### ISSUE THREAD

**Issue by UO277414** [Arquisoft/lomap_es5a#179]
Solucionar problema en el proceso de login. Se redirige correctamente a la aplicación desde el proveedor solid, pero no se almacenan correctamente los datos del usuario en sesión.

**Comment by UO277414** [comment]
Volver a emplear el hook useSession, pues el intento realizado no ha solucionado el problema.

**Comment by UO277414** [comment]
No conseguimos que se almacene la sesión cuando se refresca la página. Investigando en el foro del proyecto solid, nos encontramos con que este problema lo reportan varios usuarios.

**Comment by franciscocoya** [comment]
# Actualización

La sesión se mantiene activa al recargar la página pero, si la página es diferente a la página de inicio, es necesario recargar manualmente la página.

**Comment by UO277414** [comment]
Por el momento, continuamos con esta versión del login y cerramos esta issue
