### ISSUE TITLE
Decidir que formato seguir a la hora de almacenar los ficheros en el pod

### ISSUE THREAD

**Issue by UO277414** [Arquisoft/lomap_es5a#190]
Decidir si emplearemos un único fichero json que englobe todos los markers, amigos, grupos del usuario o si emplearemos distintos directorios dentro del pod del usuario, almacenando en cada uno varios ficheros json (uno para cada marker, uno para cada amigo, etc.).

**Comment by UO277414** [comment]
Hemos decidido almacenar los markers de cada usuario en un único fichero json. Para el almacenamiento de los amigos se empleará el FOAF:knows del pod. Falta decidir que haremos con los grupos de amigos.

**Comment by miguelglez8** [comment]
Para el caso de los puntos compartidos, se creará una carpeta sharedPoints, donde se almacenarán los puntos individuales (que el usuario decide compartir) separados en distintos json, donde se administrarán los permisos correspondientes atendiendo a la compartición de cada punto

**Comment by miguelglez8** [comment]
Para el caso de los grupos de amigos, se crearán en la carpeta groups, distintos ficheros json (uno por cada grupo), se seguirá el formato de la issue #178 de los grupos de amigos, y ahí se darán permisos a los integrantes del grupo
