### ISSUE TITLE
Solucionar bug de la categoría de los puntos (en el Parser)

### ISSUE THREAD

**Issue by UO282337** [Arquisoft/lomap_es5a#202]
Solucionar el problema del parser cuando recibimos los datos del POD, puesto que no se pueden parsear a la categoría (tipo enum) correspondiente.
- Añadir (se sube la categoría "none" en lugar de la correspondiente).
- Filtrar (obtiene un array vacío cuando debe de filtrar por la categoría).

**Comment by franciscocoya** [comment]
Solucionado ! Problema relacionado con las traducciones, asociado al valor que obtenía el selector de categorias de la vista de crear un nuevo punto. El valor se pasa en inglés mientras que el contenido (Mostrado en la cada opción del selector) en español
