### ISSUE TITLE
Seguridad: Crear funciones validación en utils/validator.ts

### ISSUE THREAD

**Issue by franciscocoya** [Arquisoft/lomap_es5a#203]
Añadir dentro del fichero las funciones de validación necesarias en la aplicación para centralizar dicha validación en este fichero, consiguiendo una mayor separación de responsabilidades en el código.

Los mensajes de error se almacenan en un objeto. 

> Importante
>
> No mostrar estos errores en la interfaz de usuario. Servirán como soporte al programador.

Ejemplo: Comprobar string no vacío.
```typescript
const checkIsNotEmpty = (value: string) => {
  if (!value || value.length === 0) {
    throw new Error(errorMessages.empty);
  }
};
```

**Comment by miguelglez8** [comment]
También se han añadido estas funciones:

/**
 * Comprueba que se ha seleccionado una opcion del combobox diferente a "Selecciona una opcion"
 * @param value Valor de la opcion seleccionada.
 * @param fieldName Nombre del campo que se está validando.
 */
const checkAnyOptionIsSelected = (value: string, fieldName: string) => {
  console.log(value);
  if (value === NO_OPTION_SELECTED) {
    throw new Error(errorMessages.empty(fieldName));
  }
};

const checkIsValidGeoCoordinate = (value: number, coord: Coordinate) => {
  const sValue = sanitizeInput(value.toString());
  //checkIsNotEmpty(sValue, coord);
  const regex = coord === Coordinate.LAT ? LAT_REGEX : LNG_REGEX;
  console.log(value, coord, regex);
  if (!regex.test(sValue)) {
    throw new Error(errorMessages.invalidGeoCoordinate);
  }
};
