### ISSUE TITLE
API. Implementación de las rutas (opcional) (DESCARTADO)

### ISSUE THREAD

**Issue by miguelglez8** [Arquisoft/lomap_es5a#234]
Permitir a los usuarios crear rutas (por ejemplo, rutas para hacer compras o tomar algo).

**Comment by miguelglez8** [comment]
Podemos realizar una comparación con una ruta de google maps, a la que el usuario va añadiendo puntos. En la lógica de negocio, vamos a crear una carpeta "routes" y dentro almacenar un único fichero "routes.json", que tenga todas las rutas que tenga ese usuario (array de rutas del usuario en sesion).

La ruta puede guardar:
- Nombre
- Descripcion
- Puntos [] (array)
- Categoria (Pensando en que pueden ser rutas de bares/restaurantes/...)
- Fecha de creacion

Teniendo esos datos, en front se podrá calcular la distancia de la ruta (es compleja pero existen fórmulas, que te permiten calcular la distancia entre dos coordenadas geográficas) u otras cosas.

**Comment by miguelglez8** [comment]
# Usar un fichero para todas las rutas

## Estructura modelo ```RUTAS```

```json
{
  "routes": [
    {
      "_id": "5a6c5b0b0f5a9c0014d1b1b1",
      "name": "Point 1",
      "description": "Point 1 description",
      "category": "",
  "points": [
      {
        "_id": "5a6c5b0b0f5a9c0014d1b1b1",
        "name": "Point 1",
        "description": "Point 1 description",
        "category": "",
        "isPublic": true,
        "location": {
          "address": "",
          "postalCode": 1111,
          "city": "City 1",
          "country": "Country 1",
          "coords": [0, 0]
        },
        "owner": {
          "webId": "https://localhost:8443/profile/card#me"
        },
        "reviews": [
          {
            "_id": "5a6c5b0b0f5a9c0014d1b1b2",
            "reviewer": {
              "webId": "https://localhost:8443/profile/card#me",
              "imageUrl": ""
            },
            "rating": 5,
            "comment": "This is a comment",
            "createdAt": "2018-01-24T15:00:00.000Z"
          }
        ],
        "createdAt": "2018-01-24T15:00:00.000Z",
        "updatedAt": "2018-01-24T15:00:00.000Z"
      }    
    ]
      "createdAt": "2018-01-24T15:00:00.000Z",
      "updatedAt": "2018-01-24T15:00:00.000Z"
    }    
  ]
}
```

**Comment by miguelglez8** [comment]
De primeras podemos realizar los siguientes métodos:
- Crear ruta
- Eliminar ruta
- Añadir punto a una ruta
- Eliminar punto de una ruta
- Editar punto de una ruta

**Comment by miguelglez8** [comment]
## Estructura directorios POD

Carpeta ```PRIVATE```

 - routes. 
    - route1.json
    - ...

**Comment by franciscocoya** [comment]
> Podemos implementar los siguientes métodos:
> 
>     * Crear ruta
> 
>     * Eliminar ruta
> 
>     * Añadir punto a una ruta
> 
>     * Eliminar punto de una ruta
> 
>     * Editar ruta (algún punto o demás)

No pondría editar la ruta. Los métodos que implementaría en su lugar, son los siguientes:

- *Crear una nueva ruta*. A partir de unos puntos seleccionados previamente.
- *Añadir un nuevo punto a la ruta*. Por simplificar, restringir a que el punto se añada a una ruta existente, sin necesidad de crear la ruta en caso de que ésta no exista.
- *Listar todos los puntos de la ruta*.
- * Eliminar un punto de la ruta*. Recibir id del punto e id de la ruta.
- *Cambiar el orden de un punto de interés en la ruta*.

**Comment by franciscocoya** [comment]
> Podemos realizar una comparación con una ruta de google maps, a la que el usuario va añadiendo puntos. En la lógica de negocio, vamos a crear una carpeta "routes" y dentro almacenar un único fichero "routes.json", que tenga todas las rutas que tenga ese usuario (array de rutas del usuario en sesion).
> 
> La ruta puede guardar:
> 
>     * Id de la ruta
> 
>     * Nombre
> 
>     * Descripcion
> 
>     * Categoria (Pensando en que pueden ser rutas de bares/restaurantes/...)
> 
>     * Puntos [] (array)
> 
>     * Fecha de creacion
> 
>     * Fecha de actualizacion
> 
> 
> Teniendo esos datos, en front se podrá calcular la distancia de la ruta (es compleja pero existen fórmulas, que te permiten calcular la distancia entre dos coordenadas geográficas) u otras cosas.

Añadiría también, si es posible, un campo orden, que permita al usuario intercambiar el recorrido, por ejemplo, para hacerlo más corto. 

Referencia: Google Maps. Permite arrastrar las paradas (En nuestro caso puntos) para cambiar la ruta.
![imagen](https://user-images.githubusercontent.com/56480356/232027723-de2c8fa4-c159-4d24-8532-f59616909ad0.png)
