### ISSUE TITLE
Fix: Timeout de 5 segundos, habilite botón de publicar y se borre los campos del formulario

### ISSUE THREAD

**Issue by miguelglez8** [Arquisoft/lomap_es5a#302]
ACLARACIÓN: también limpien los errores cuando añades el punto para que solo aparezca el error actual
ERRORES: combobox, filtro del mapa, logout (actualizar el enlace solo dejando el localhost sin el /login) y al subir una imagen que se borre la imagen que había antes cuando añades otro punto.

**Comment by UO271572** [comment]
Añadido el timeout

**Comment by franciscocoya** [comment]
Realizado en #399 

Además, se ha añadido una comprobación para el tipo mime del fichero subido como imagen del punto, para permitir sólamente los formatos especificados de imagen.
