### ISSUE TITLE
Implementación de los test de carga en Gatling

### ISSUE THREAD

**Issue by miguelglez8** [Arquisoft/lomap_es5a#334]

**Comment by UO271572** [comment]
Configuracion para los tests de carga:
En Firefox realizar los siguentes ajustes
![image](https://user-images.githubusercontent.com/91533653/235320817-00966382-2b1f-482e-84b3-579969519424.png)
![image](https://user-images.githubusercontent.com/91533653/235320827-0e2a1d19-f61e-4861-9a0d-0d4ecb27acc1.png)
Descargar gatling y ejecutar recorder.bat
![image](https://user-images.githubusercontent.com/91533653/235320887-ff98211e-c184-4d15-a0a1-16d8f29ce2d0.png)

**Comment by UO271572** [comment]
Tras dar a start aparece el siguente problema:
![image](https://user-images.githubusercontent.com/91533653/235320927-0231e64c-7ea3-4175-98f4-2628374969e5.png)

Si modificamos network.proxy.allow_hijacking_localhost por false obtenemos:
![image](https://user-images.githubusercontent.com/91533653/235320964-6db3a5bf-f4b1-402c-b65d-672c07a50a2f.png)
Al acceder a inrupt o solid aparece en la consola el error.

**Comment by UO271572** [comment]
Solucionado el error. Se ha utilizado la opcion de chrome para grabar las peticiones realizadas. A traves del despliegue en [lomap](https://franciscocoya.github.io/lomapes05a_production/)
![image](https://user-images.githubusercontent.com/91533653/235324398-f51f6339-a945-4392-9725-f80b1d16c28f.png)
Tras finalizar la simulacion hacer click en las descargas(a la derecha del simbolo de wifi).
Volvemos a gatling para convertir el archivo.HAR en codigo java.
![image](https://user-images.githubusercontent.com/91533653/235324442-a5b1849a-3343-4f64-b700-3334411679b2.png)
Ahora se procedera con normalidad a agregar la carga para estos test que se han grabado.
Ejecutar el gatling.bat con el archivo java y se generara las graficas con los datos de la medicion.
