### ISSUE TITLE
problema cors con firebase

### ISSUE THREAD

**Issue by miguelglez8** [Arquisoft/lomap_es5a#345]
**Solución:**
- Creación de la cuenta de firebase común
- Creación de fichero de propiedades (.env.development)
- Instalar shell de Google Cloud
- Ejecutar los siguientes comandos:
1. echo [{"origin": ["*"],"responseHeader": ["Content-Type"],"method": ["GET", "HEAD", "POST"],"maxAgeSeconds": 3600}] > cors-config.json
2. gsutil cors set cors-config.json gs://lomapes05a-5b754.appspot.com
3. gsutil cors get gs://lomapes05a-5b754.appspot.com

**Comment by UO271572** [comment]
Por si sirve de ayuda, esto es lo que tengo en otro proyecto en node 
![image](https://user-images.githubusercontent.com/91533653/233776294-584d4a4b-bb7b-498e-9cee-7185c12407c3.png)
