### ISSUE TITLE
bug: Al añadir un punto, no se guardan correctamente los amigos

### ISSUE THREAD

**Issue by franciscocoya** [Arquisoft/lomap_es5a#368]
Se muestra el siguiente error. Parece como si no me estuviera obteniendo bien los amigos o simplemente, que me falle internamente algo que desconozco. El error que muestra por consola es el siguiente, aunque el punto lo añade correctamente.

![imagen](https://user-images.githubusercontent.com/56480356/234360387-5833dae3-c49d-4969-95b7-166eebb0531a.png)

**Comment by RichardPix12** [comment]
El problema estaba en los puntos mockeados para probar nosotros, no funciona ahora por el cambio de añadir isOwner, y los amigos, por tanto hay que borrarlos, y crear tu unos nuevos desde la aplicacion, ppr tanto lo recomedable es crearlos desde 0.
![image](https://user-images.githubusercontent.com/79644476/234565952-c9acce71-4f86-4b4c-ad68-6cd7f9530ba2.png)
