### ISSUE TITLE
chore: Solucionar funcionalidades perdidas

### ISSUE THREAD

**Issue by franciscocoya** [Arquisoft/lomap_es5a#369]
último commit funcional:

![imagen](https://user-images.githubusercontent.com/56480356/234416344-0bf044a7-e5bd-4ad7-b5bf-ff3ab65b9ac6.png)

**Comment by RichardPix12** [comment]
El problema estaba en los puntos mockeados para probar nosotros, no funciona ahora por el cambio de añadir isOwner, y los amigos, por tanto hay que borrarlos, y crear tu unos nuevos desde la aplicacion

**Comment by RichardPix12** [comment]
No hay ningun error de funcionalidad perdida
