### ISSUE TITLE
Arreglar test SingleDetails - GitHubWorkFlow

### ISSUE THREAD

**Issue by miguelglez8** [Arquisoft/lomap_es5a#377]

**Comment by franciscocoya** [comment]
# Revisar

- [ ] Buscar amigo (Añadir). Se capturan los errores propagados en la API ? 
- [ ] La sesión está activa, capturando el webId del usuario ?

# Pasos previos

Antes del error se toco el componente BaseSelect y BaseMapPopup (Mostrar icono save de forma condicional).
