### ISSUE TITLE
bug: Gestionar error si Firebase no está operativo o errores derivados

### ISSUE THREAD

**Issue by franciscocoya** [Arquisoft/lomap_es5a#385]
# Incidencia

En este caso, las variables de entorno de Firebase no existían, lo que hace imposible subir una imagen. El botón de publicar no se llega a habilitar nunca debido a una mala configuración del estado que habilita/deshabilita dicho componente.

![imagen](https://user-images.githubusercontent.com/56480356/235310090-1e2bfab3-5c28-4004-9209-ffd46fb0ea81.png)

**Comment by miguelglez8** [comment]
Ya está funcionando con imágenes.
