### ISSUE TITLE
Bug: Al compartir un punto

### ISSUE THREAD

**Issue by UO271572** [Arquisoft/lomap_es5a#391]
Compartir un punto con un amigo hace que al iniciar sesion con el amigo compartido, este sea el dueño del punto y por tanto tampoco le deja añadir valoraciones

**Comment by UO271572** [comment]
![image](https://user-images.githubusercontent.com/91533653/235355917-6713d2d8-f66f-4372-b55e-4d92ac74bfb3.png)

**Comment by RichardPix12** [comment]
![image](https://user-images.githubusercontent.com/79644476/235429728-878819b9-3f7d-43d4-b671-eb511a92b99a.png)
A mi me comparten este punto y me funciona bien.
