### ISSUE TITLE
Bug: No se pueden añadir reviews en puntos compartidos

### ISSUE THREAD

**Issue by RichardPix12** [Arquisoft/lomap_es5a#402]
Cambiar el metodo de añadir review, y de eliminar review para poder trabajar con las reviews

- [x] Se trabajaria en una carpeta del Owner del punto, que tendria permisos todos [Miguel]
- [x] Las comprobaciones de si se pueden añadir y eliminar se harian en el front [Richard]
- [x] Arreglar test que falla [Richard y Miguel]

**Comment by miguelglez8** [comment]
Las reviews pasarían a estar en la carpeta public, en un fichero reviews.json

**Comment by RichardPix12** [comment]
Arreglado el BUG
