### ISSUE TITLE
Configuración Base de datos local Mongo

### ISSUE THREAD

**Issue by UO277414** [Arquisoft/lomap_es5a#49]
Intentar configurar base de datos local para desarrollo de la API REST.

**Comment by UO277414** [comment]
He conseguido crear la base de datos local. Falta conectarse y realizar alguna prueba.

**Comment by UO277414** [comment]
Al final hemos optado por emplear MongoDB Atlas. Ya está configurado y probado.

**Comment by UO282337** [comment]
He conseguido conectarme también e insertar datos de prueba de los puntos, adjunto pruebas:
![image](https://user-images.githubusercontent.com/113930788/223694847-1e5a53ca-1dba-4b2e-b968-116fc3ecd79c.png)
