### ISSUE TITLE
Página de Acerca de

### ISSUE THREAD

**Issue by franciscocoya** [Arquisoft/lomap_es5a#83]
## Tareas

- [x] Creación de la interfaz de usuario de página "Acerca de" de la aplicación.

**Comment by RichardPix12** [comment]
![image](https://user-images.githubusercontent.com/79644476/223087639-3f814e23-7da9-4155-97a2-c002c0dce2c8.png)
Prototipo creado en figma

**Comment by RichardPix12** [comment]
Creada y terminada
